spring:
  application:
    name: dispatcher

server:
  port: 8888

bonus:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9000,localhost:9001
    ServerListRefreshInterval: 15000
