logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  tomcat:
    max-threads: 2000


